env:
  commonjs: true
  es6: true
  mocha: true
  jasmine: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
