sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "node"
  - "lts/*"

before_instnall:
  - echo '' > .npmrc

install: npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
