sudo: false
language: node_js
node_js:
  # - "0.10"
  # - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
before_instnall:
  - echo '' > .npmrc
install: npm install
script:
  - npm run test
git:
  depth: 10
